local LSM = LibStub("LibSharedMedia-3.0")
local base = [[Interface\AddOns\MiniMeter\Fonts\]]

LSM:Register("font", "Accidental Presidency",   base .. [[Accidental_Presidency.ttf]])
LSM:Register("font", "Action Man",              base .. [[ActionMan.ttf]])
LSM:Register("font", "Alba Super",              base .. [[ALBAS___.ttf]])
LSM:Register("font", "Arm Wrestler",            base .. [[ArmWrestler.ttf]])
LSM:Register("font", "Avant Garde LT Book",     base .. [[AvantGarde_LT_Book_Regular.ttf]])
LSM:Register("font", "Baars",                   base .. [[BAARS___.TTF]])
LSM:Register("font", "Blazed",                  base .. [[Blazed.ttf]])
LSM:Register("font", "Boris Black Bloxx",       base .. [[BorisBlackBloxx.ttf]])
LSM:Register("font", "Boris Black Bloxx Dirty", base .. [[BorisBlackBloxxDirty.ttf]])
LSM:Register("font", "Cabin",                   base .. [[Cabin-Regular.ttf]])
LSM:Register("font", "Celestia Medium Redux",   base .. [[CelestiaMediumRedux1_55.ttf]])
LSM:Register("font", "Century Gothic",          base .. [[centurygothic.ttf]])
LSM:Register("font", "Collegia",                base .. [[COLLEGIA.ttf]])
LSM:Register("font", "Continuum Medium",        base .. [[ContinuumMedium.ttf]])
LSM:Register("font", "DejaVu Sans",             base .. [[DejaVuSans.ttf]])
LSM:Register("font", "DejaVu Sans Bold",        base .. [[DejaVuSans-Bold.ttf]])
LSM:Register("font", "Die Die Die",             base .. [[DieDieDie.ttf]])
LSM:Register("font", "Diogenes",                base .. [[DIOGENES.ttf]])
LSM:Register("font", "Disko",                   base .. [[Disko.ttf]])
LSM:Register("font", "Expressway Bold",         base .. [[Expressway-Bold.ttf]])
LSM:Register("font", "Fraks",                   base .. [[FRAKS___.ttf]])
LSM:Register("font", "Gotham Narrow Ultra",     base .. [[GothamNarrow-Ultra.ttf]])
LSM:Register("font", "Homespun",                base .. [[Homespun.ttf]])
LSM:Register("font", "Impact",                  base .. [[impact.ttf]])
LSM:Register("font", "JetBrains Mono",          base .. [[JetBrainsMono-Regular.ttf]])
LSM:Register("font", "Liberation Sans",         base .. [[LiberationSans-Regular.ttf]])
LSM:Register("font", "Liberation Serif",        base .. [[LiberationSerif-Regular.ttf]])
LSM:Register("font", "Mystik Orbs",             base .. [[MystikOrbs.ttf]])
LSM:Register("font", "Nanum Gothic",            base .. [[NanumGothic-Regular.ttf]])
LSM:Register("font", "Nunito",                  base .. [[Nunito-Regular.ttf]])
LSM:Register("font", "Pokemon Solid",           base .. [[Pokemon_Solid.ttf]])
LSM:Register("font", "Prototype",               base .. [[Prototype.ttf]])
LSM:Register("font", "PT Sans Narrow Bold",     base .. [[PTSansNarrow-Bold.ttf]])
LSM:Register("font", "Roboto Condensed Bold",   base .. [[RobotoCondensed-Bold.ttf]])
LSM:Register("font", "Rock Show Whiplash",      base .. [[Rock_Show_Whiplash.ttf]])
LSM:Register("font", "SF Diego Sans",           base .. [[SF_Diego_Sans.ttf]])
LSM:Register("font", "Solange",                 base .. [[Solange.ttf]])
LSM:Register("font", "Starcine",                base .. [[starcine.ttf]])
LSM:Register("font", "Trashco",                 base .. [[trashco.ttf]])
LSM:Register("font", "Ubuntu Condensed",        base .. [[Ubuntu-C.ttf]])
LSM:Register("font", "Ubuntu Light",            base .. [[Ubuntu-L.ttf]])
LSM:Register("font", "Verdana",                 base .. [[Verdana.ttf]])
LSM:Register("font", "Yanone Kaffeesatz",       base .. [[YanoneKaffeesatz-Regular.ttf]])
